# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_progress.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_progressDialog(object):
    def setupUi(self, progressDialog):
        progressDialog.setObjectName("progressDialog")
        progressDialog.resize(826, 528)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(progressDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBoxLog = QtWidgets.QGroupBox(progressDialog)
        self.groupBoxLog.setObjectName("groupBoxLog")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxLog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textLog = QtWidgets.QTextBrowser(self.groupBoxLog)
        self.textLog.setObjectName("textLog")
        self.verticalLayout.addWidget(self.textLog)
        self.layoutLabels = QtWidgets.QHBoxLayout()
        self.layoutLabels.setObjectName("layoutLabels")
        self.labelStatusTitle = QtWidgets.QLabel(self.groupBoxLog)
        self.labelStatusTitle.setMaximumSize(QtCore.QSize(61, 17))
        self.labelStatusTitle.setObjectName("labelStatusTitle")
        self.layoutLabels.addWidget(self.labelStatusTitle)
        self.labelStatusBody = QtWidgets.QLabel(self.groupBoxLog)
        self.labelStatusBody.setObjectName("labelStatusBody")
        self.layoutLabels.addWidget(self.labelStatusBody)
        self.verticalLayout.addLayout(self.layoutLabels)
        self.verticalLayout_2.addWidget(self.groupBoxLog)
        self.layoutBtns = QtWidgets.QHBoxLayout()
        self.layoutBtns.setObjectName("layoutBtns")
        self.layoutBtnsExtra = QtWidgets.QHBoxLayout()
        self.layoutBtnsExtra.setObjectName("layoutBtnsExtra")
        self.btnExportLog = QtWidgets.QPushButton(progressDialog)
        self.btnExportLog.setObjectName("btnExportLog")
        self.layoutBtnsExtra.addWidget(self.btnExportLog)
        self.btnModelOutput = QtWidgets.QPushButton(progressDialog)
        self.btnModelOutput.setObjectName("btnModelOutput")
        self.layoutBtnsExtra.addWidget(self.btnModelOutput)
        self.layoutBtns.addLayout(self.layoutBtnsExtra)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutBtns.addItem(spacerItem)
        self.btnDialogBox = QtWidgets.QDialogButtonBox(progressDialog)
        self.btnDialogBox.setOrientation(QtCore.Qt.Horizontal)
        self.btnDialogBox.setStandardButtons(QtWidgets.QDialogButtonBox.Abort|QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Reset)
        self.btnDialogBox.setObjectName("btnDialogBox")
        self.layoutBtns.addWidget(self.btnDialogBox)
        self.verticalLayout_2.addLayout(self.layoutBtns)

        self.retranslateUi(progressDialog)
        self.btnDialogBox.accepted.connect(progressDialog.accept)
        self.btnDialogBox.rejected.connect(progressDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(progressDialog)

    def retranslateUi(self, progressDialog):
        _translate = QtCore.QCoreApplication.translate
        progressDialog.setWindowTitle(_translate("progressDialog", "Estimation progress"))
        self.groupBoxLog.setTitle(_translate("progressDialog", "Progress log"))
        self.labelStatusTitle.setText(_translate("progressDialog", "<html><head/><body><p><strong>Status:</strong></p></body></html>"))
        self.labelStatusBody.setText(_translate("progressDialog", "<html><head/><body><p><span style=\" color:#0000ff;\">Optimizing</span></p></body></html>"))
        self.btnExportLog.setText(_translate("progressDialog", "Export log"))
        self.btnModelOutput.setText(_translate("progressDialog", "Model output"))
